name: p1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  firebase_core: ^3.6.0
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.3.3
  image_picker: ^1.1.2
  google_sign_in: ^6.2.1
  firebase_ui_oauth_google: ^1.4.0
  sign_in_button: ^3.2.0
  cupertino_icons: ^1.0.2
  flutter_tts: ^4.1.0 
  http: ^1.2.2
  just_audio: ^0.9.42
  youtube_explode_dart: ^2.3.6
  google_generative_ai: ^0.4.6
  youtube_player_flutter: ^9.1.1
  tflite_flutter: ^0.11.0
  camera: ^0.11.0+2
  image: ^4.5.2
  file_picker: ^8.1.7
  jwt_decoder: ^2.0.1
  dart_jsonwebtoken: ^2.16.0
  ffmpeg_kit_flutter: ^6.0.3
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  path_provider: ^2.1.5
  path_drawing: ^1.0.1
  percent_indicator: ^4.2.3
  intl: ^0.15.2
  connectivity_plus: ^6.1.3

dependency_overrides:
  intl: 0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/cedict_ts.u8
    - lib/assets/labels.txt
    - assets/credentials/google_cloud_credentials.json
    - lib/assets/hanzi-strokes/dictionary.txt
    - lib/assets/hanzi-strokes/graphics.txt